### PR TITLE
feat: add module and typings entry items

### PR DESCRIPTION
**Pull request by will-stone**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [x] yes
- [ ] no

I think it's a "yes". It will move users' package keys, so I'm gonna go with yes.

### Please Describe Your Changes

This will sort the "module" and "typings" items to be with the other _entry_ items.

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for putting this together. For `typings` I've known that I want to mutate that to `types` based on [this TypeScript style guide](https://github.com/sindresorhus/typescript-definition-style-guide).

Please allow me some time to research and compare against some of Sindre's work for the placement of `module`.

**Comment by will-stone** [comment]
Ah, did not know that about "typings", thanks. Yeah, updating this automatically would be nice. Let me know if you'd like me to look into that.

**Comment by shellscape** [comment]
We've got an answer on where `types` should go https://github.com/sindresorhus/typescript-definition-style-guide/issues/11. That's traditionally where I've placed mine, and I think the after [official properties](https://docs.npmjs.com/files/package.json) is a good distinction.

There seems to be some confusion surrounding `module` and whether or not it's official. I know that it's a first-class citizen within webpack, and I'm going to get with the Rollup team today to see how that's treated. If it's treated as a "universally" supported entry point with everything but the official npm docs (I suspect so) I'm good with where it's at.

**Comment by will-stone** [comment]
I've moved "typings" to bottom (before custom) and added "types" too; keeping both until the auto-mutation is made.

**Pull request merged**
