### PR TITLE
Add support to peerDependenciesMeta

### LINKED ISSUE #10: Add support for peerDependenciesMeta
### Feature Use Case

Right now `peerDependenciesMeta` appears at the bottom

### Feature Proposal

I propose it add it under `peerDependencies`.

### PR DESCRIPTION
**Pull request by abdonrd**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [ ] yes
- [x] no

If yes, please describe the breakage.

### Please Describe Your Changes

Fix #10

### CODE REVIEW

**Comment by shellscape** [comment]
Please provide a link to NPM documentation or an NPM specification that details the `peerDependenciesMeta` property. Please note that it must be for NPM proper, and not a third party package manager.

**Comment by abdonrd** [comment]
@shellscape I found it here at the npm blog:

https://blog.npmjs.org/post/186983646370/npm-cli-roadmap-summer-2019

>New features likely to land on the 6.x branch:
>
>Add support for the peerDependenciesMeta field. ([#224](https://github.com/npm/cli/pull/224))

Also here in the changelog:

https://github.com/npm/cli/releases/tag/v6.11.0

Also the release announcement:

https://npm.community/t/release-6-11-0/9572

But I can't find it in the docs.

**Comment by abdonrd** [comment]
I just created an issue to request docs: https://github.com/npm/cli/issues/1247

**Comment by shellscape** [comment]
👍 Let's wait to see what they say about updating the docs.

**Comment by abdonrd** [comment]
Ok! But isn't the blog and changelog enough to support it? I say this because seeing the issues they have, it seems that they take a long time to respond...

Thanks in advance and thank for the plugin!

**Comment by shellscape** [comment]
I'll see what I can do to get eyes on that through back channels. NPM _supports_ a ton of properties so things don't break, but the list of properties that are first-class official NPM properties that are the baseline for an NPM package is pretty short.

It's a bit of a rabbit hole to support all possible properties in this plugin, so a baseline is needed, which is why I go from the docs or accepted spec from NPM itself.

**Comment by abdonrd** [comment]
Got it, thanks again!

**Comment by abdonrd** [comment]
In case this information helps you, we have just started using that property to avoid the warnings that the official NPM CLI gives when you do not install all the peer dependencies.

If we do not use this property, it is the official NPM CLI that shows us the warning.

**Comment by abdonrd** [comment]
More info, also the `package-lock.json` changes with this:

Screenshot 2020-05-05 at 15 20 51

You can see how the `requires` object is different now.

**Comment by abdonrd** [comment]
@shellscape official documentation is coming! https://github.com/npm/cli/pull/1822

**Comment by shellscape** [comment]
that's great. since it's got acknowledgement from NPM, we can add support here. Please do update the README and we should be good.

**Comment by abdonrd** [comment]
@shellscape done!

**Pull request merged**
