### PR TITLE
feat: sort dependencies

### PR DESCRIPTION
**Pull request by will-stone**
This PR contains:

- [ ] bugfix
- [x] feature
- [ ] refactor
- [ ] tests
- [ ] documentation
- [ ] metadata

### Breaking Changes?

- [x] yes
- [ ] no

If users' dependencies are not alphabetically sorted, they will notice changes.

### Please Describe Your Changes

Will alphabetically sort dependencies. Issue: #2

### CODE REVIEW

**Comment by shellscape** [comment]
Thanks for opening a PR :beer:

I'm still of the opinion that the solution in [my comment on #2](https://github.com/shellscape/prettier-plugin-package/issues/2#issuecomment-532897752) would invariably be the most flexible solution for this. I don't believe the extra processing here is going to be necessary in most cases, and an option to specify additional property values to sort would cover the edge cases.

**Comment by will-stone** [comment]
At the end of the day, it's your plugin so I'm happy to go with your judgement. However my counter-argument would be that we're already being very opinionated with ordering and so why stop at high-level keys? Especially as `yarn` and `npm` like to sort the keys in this way too. I'll leave this with you, feel free to tweak PR if you go down the opt-in route.

**Comment by shellscape** [comment]
> Especially as yarn and npm like to sort the keys in this way too. 

That's precisely why I'm hesitant. The package managers all handle this. I'd argue the edge case here is manually adding dependencies out of order to those arrays. It's not something that most users are going to do, so processing those arrays isn't something we should do on every run.

**Comment by will-stone** [comment]
Right, gotcha. Yeah, maybe this isn't so useful. Feel free to close if this all seems like overkill.

**Comment by shellscape** [comment]
If you're up for it, I'd like to change this to provide that `sortAlpha` option. You've already laid most of the groundwork in your changes already.

**Comment by will-stone** [comment]
Sure. Will do...

**Comment by will-stone** [comment]
I had a go but couldn't figure out how to get the option to pass through to the plugin.

**Comment by shellscape** [comment]
OK let's keep this open. I'll follow up later today or tomorrow AM.

**Comment by shellscape** [comment]
OK so I'm not sure why this didn't automatically close, but your changes were merged in on 5df5f77b127f8e6e14ae7f413a8ef83abe20008d. I chose to merge this as an intermediate step to the custom sort spec.

**Comment by shellscape** [comment]
So I've done the leg work for allowing custom sorting on the `feat/sort-custom` branch. Unfortunately, some shortsightedness by the Prettier team with regard to options has me pretty stuck. See https://github.com/prettier/prettier/issues/6151

I need to give this some thought. We can't specify an `object` option, which would be ideal, so we'd have to use a really hacky end-around the problem: either have to have separate options for each sort method (e.g. `sort-alpha` or `sortAlpha`) and make users use a comma-separated string or some such, or maybe JSON. No good alternatives come to mind, so I'll have to think on it a bit.

**Comment by will-stone** [comment]
Okay, thanks for looking into it.

**Pull request closed without merging**
